export const data = [
    {
        "id": "1",
        "name": "Spicy Delight",
        "locality": "Downtown",
        "areaName": "City Center",
        "costForTwo": "₹300 for two",
        "cuisines": ["Indian", "Chinese"],
        "avgRating": 4.2,
        "totalRatings": "5K+",
        "deliveryTime": 30,
        "lastMileTravel": 3.0,
        "isOpen": true,
        "image": "https://wallpaperaccess.com/full/7066805.jpg"
    },
    {
        "id": "2",
        "name": "Pizza Palace",
        "locality": "Uptown",
        "areaName": "North Side",
        "costForTwo": "₹500 for two",
        "cuisines": ["Italian", "Fast Food"],
        "avgRating": 4.5,
        "totalRatings": "10K+",
        "deliveryTime": 25,
        "lastMileTravel": 2.5,
        "isOpen": true,
        "image": "https://wallpaperaccess.com/full/826922.jpg"
    },
    {
        "id": "3",
        "name": "Burger Hub",
        "locality": "Midtown",
        "areaName": "Central Park",
        "costForTwo": "₹400 for two",
        "cuisines": ["American", "Fast Food"],
        "avgRating": 4.0,
        "totalRatings": "8K+",
        "deliveryTime": 20,
        "lastMileTravel": 1.5,
        "isOpen": true,
        "image": "https://www.fusion6.com.au/wp-content/uploads/2021/04/Indian-Dishes-You-Need-to-Try.jpg"
    },
    {
        "id": "4",
        "name": "Sushi World",
        "locality": "East End",
        "areaName": "Riverside",
        "costForTwo": "₹600 for two",
        "cuisines": ["Japanese", "Asian"],
        "avgRating": 4.8,
        "totalRatings": "3K+",
        "deliveryTime": 35,
        "lastMileTravel": 4.0,
        "isOpen": true,
        "image": "https://tse3.mm.bing.net/th?id=OIP.jWYZvYZxWilTDrwfTRRG7gHaEY&pid=Api&P=0&h=180"
    },
    {
        "id": "5",
        "name": "Taco Fiesta",
        "locality": "West End",
        "areaName": "Beachside",
        "costForTwo": "₹350 for two",
        "cuisines": ["Mexican"],
        "avgRating": 4.3,
        "totalRatings": "6K+",
        "deliveryTime": 28,
        "lastMileTravel": 2.8,
        "isOpen": true,
        "image": "https://cdn10.phillymag.com/wp-content/uploads/sites/3/2019/02/best-indian-restaurant-philadelphia.jpg"
    },
    {
        "id": "6",
        "name": "Pasta Paradise",
        "locality": "Old Town",
        "areaName": "Historic District",
        "costForTwo": "₹450 for two",
        "cuisines": ["Italian"],
        "avgRating": 4.6,
        "totalRatings": "7K+",
        "deliveryTime": 22,
        "lastMileTravel": 1.8,
        "isOpen": true,
        "image": "https://tse1.mm.bing.net/th?id=OIP.26Zu3vzbFOuDq26KZpcLUwHaD4&pid=Api&P=0&h=180"
    },
    {
        "id": "7",
        "name": "Curry House",
        "locality": "New Town",
        "areaName": "Tech Park",
        "costForTwo": "₹250 for two",
        "cuisines": ["Indian"],
        "avgRating": 4.1,
        "totalRatings": "4K+",
        "deliveryTime": 18,
        "lastMileTravel": 1.2,
        "isOpen": true,
        "image": "https://tse4.mm.bing.net/th?id=OIP.5oq3IfXZu7cZnQQIFkvDrwHaE8&pid=Api&P=0&h=180"
    },
    {
        "id": "8",
        "name": "BBQ Nation",
        "locality": "Suburb",
        "areaName": "Green Valley",
        "costForTwo": "₹700 for two",
        "cuisines": ["Barbecue", "Grill"],
        "avgRating": 4.7,
        "totalRatings": "9K+",
        "deliveryTime": 40,
        "lastMileTravel": 5.0,
        "isOpen": true,
        "image": "https://tse2.mm.bing.net/th?id=OIP.S2rYKAMEiiJqI_YKlKnDfwHaE8&pid=Api&P=0&h=180"
    },
    {
        "id": "9",
        "name": "Vegan Delight",
        "locality": "Eco Park",
        "areaName": "Nature's Nest",
        "costForTwo": "₹350 for two",
        "cuisines": ["Vegan", "Healthy"],
        "avgRating": 4.4,
        "totalRatings": "2K+",
        "deliveryTime": 30,
        "lastMileTravel": 3.2,
        "isOpen": true,
        "image": "https://tse1.mm.bing.net/th?id=OIP.E-C8QPf2gUc5AyS8B-XVfAHaE7&pid=Api&P=0&h=180"
    },
    {
        "id": "10",
        "name": "Dessert Haven",
        "locality": "Sweet Street",
        "areaName": "Candy Land",
        "costForTwo": "₹200 for two",
        "cuisines": ["Desserts"],
        "avgRating": 4.9,
        "totalRatings": "1K+",
        "deliveryTime": 15,
        "lastMileTravel": 1.0,
        "isOpen": true,
        "image": "https://tse3.mm.bing.net/th?id=OIP.mFjIvbdfKxTmekIpO6VbGQHaE8&pid=Api&P=0&h=180"
    }
];